import { CubeIcon } from '@heroicons/react/solid'
import cx from 'classnames'
import Head from 'next/head'
import Link from 'next/link'

import ThemeToggler from '@/components/ThemeToggler'
import styles from '@/styles/Home.module.css'

function HiddenIcon({}) {
  return <CubeIcon className={styles.cubeIcon} />
}

export default function Header({}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={cx(styles.header)}>
        <HiddenIcon />
        <Link href="/">Header</Link>
        <ThemeToggler />
      </header>
    </>
  )
}
